name: build and push srawler image

on:
  push:
    paths:
      - 'search_engine_crawler/**.txt'
      - 'search_engine_crawler/crawler/**.py'
      - 'search_engine_crawler/tests/**.py'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./search_engine_crawler/Dockerfile
          push: true
          tags: devopstank/crawler:latest