name: build and push crawler-ui image

on:
  push:
    paths:
      - 'search_engine_ui/**.txt'
      - 'search_engine_ui/ui/**.py'
      - 'search_engine_ui/tests/**.py'
      - 'search_engine_ui/ui/templates/**.html'
      - 'search_engine_ui/Dockerfile'
jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./search_engine_ui
          file: ./search_engine_ui/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/crawler-ui:1.2
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: Docker

    steps:
      - uses: actions/checkout@v1
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

      - uses: actions-hub/kubectl@master
        with:
          args: apply -f ./kubernetes